---

- name: Delete any existing management pod
  k8s:
    name: "{{ meta.name }}-db-management"
    kind: Pod
    namespace: "{{ backup_pvc_namespace }}"
    state: absent
    force: true

- name: Remove ownerReferences from secrets to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ item }}'
        namespace: '{{ meta.namespace }}'
        ownerReferences: null
  loop:
    - '{{ secret_key_secret_name }}'
    - '{{ admin_password_secret_name }}'
    - '{{ broadcast_websocket_secret_name }}'
    - '{{ postgres_configuration_secret_name }}'
