---

- name: Get secret definition from pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "cat '{{ backup_dir }}/secrets.yml'"
  register: secrets

- name: Create temp vars file
  tempfile:
    prefix: secret_vars-
  register: secret_vars

- name: Write vars to file locally
  copy:
    dest: "{{ secret_vars.path }}"
    content: "{{ secrets.stdout }}"
    mode: 0640

- name: Include secret vars from backup
  include_vars: "{{ secret_vars.path }}"

- name: Set new database host based on supplied deployment_name
  set_fact:
    database_host: "{{ deployment_name }}-postgres"
  when:
    - database_type == 'managed'

- name: Apply secret
  k8s:
    state: present
    namespace: "{{ meta.namespace }}"
    apply: yes
    wait: yes
    template: "secrets.yml.j2"
