---

- name: Get Secret Name
  set_fact:
      _name: "{{ awx_spec[item] | default('') }}"

- name: Skip if secret name not defined
  block:
      - name: Get secret
        k8s_info:
            version: v1
            kind: Secret
            namespace: '{{ meta.namespace }}'
            name: "{{ _name }}"
        register: _secret

      - name: Set secret key
        set_fact:
            _data: "{{ _secret['resources'][0]['data'] }}"

      - name: Create and Add secret names and data to dictionary
        set_fact:
            secret_dict: "{{ secret_dict | default({}) | combine({item: { 'name': _name, 'data': _data }}) }}"
  when: _name != ''
