---

- name: Determine the timestamp
  set_fact:
    now: '{{ lookup("pipe", "date +%FT%TZ") }}'

- name: Emit ocp event with error
  k8s:
    kind: Event
    namespace: "{{ meta.namespace }}"
    template: "event.yml.j2"
