---
name: Bug Report
description: "🐞 Create a report to help us improve"
body:
  - type: markdown
    attributes:
      value: |
        Bug Report issues are for **concrete, actionable bugs** only.
        For debugging help or technical support, please see the [Get Involved section of our README](https://github.com/ansible/awx-operator#get-involved)

  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label: I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
          required: true
        - label: I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
          required: true
        - label: I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the problem.
    validations:
      required: false

  - type: input
    id: awx-operator-version
    attributes:
      label: AWX Operator version
      description: What version of the AWX Operator are you running?
    validations:
      required: true

  - type: input
    id: awx-version
    attributes:
      label: AWX version
      description: What version of AWX are you running?
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Kubernetes platform
      description: What platform did you install the Operator in?
      multiple: false
      options:
        - kubernetes
        - minikube
        - openshift
        - minishift
        - docker development environment
        - other (please specify in additional information)
    validations:
      required: true

  - type: input
    id: kube-version
    attributes:
      label: Kubernetes/Platform version
      description: What version of your platform/kuberneties are you using?
    validations:
      required: true

  - type: dropdown
    id: modified-architecture
    attributes:
      label: Modifications
      description: >-
       Have you modified the installation, deployment topology, or container images in any way? If yes, please
       explain in the "additional information" field at the bottom of the form.
      multiple: false
      options:
        - "no"
        - "yes"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Starting from a new installation of the system, describe exactly how a developer or quality engineer can reproduce the bug
        on infrastructure that isn't yours. Include any and all resources created, input values, test users, roles assigned, playbooks used, etc.
    validations:
      required: true

  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: What did you expect to happpen when running the steps above?
    validations:
      required: true

  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Include any relevant log output, links to sosreport, database dumps, screenshots, AWX spec yaml, or other information.
    validations:
      required: false

  - type: textarea
    id: operator-logs
    attributes:
      label: Operator Logs
      description: Include any relevant logs generated by the operator.
    validations:
      required: false
