apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awxbackups.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWXBackup
    listKind: AWXBackupList
    plural: awxbackups
    singular: awxbackup
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Schema validation for the AWXBackup CRD
        properties:
          spec:
            required:
              - deployment_name
            properties:
              backup_pvc:
                description: Name of the PVC to be used for storing the backup
                type: string
              backup_pvc_namespace:
                description: Namespace PVC is in
                type: string
              backup_storage_class:
                description: Storage class to use when creating PVC for backup
                type: string
              backup_storage_requirements:
                description: Storage requirements for the PostgreSQL container
                type: string
              deployment_name:
                description: Name of the deployment to be backed up
                type: string
              postgres_label_selector:
                description: Label selector used to identify postgres pod for backing
                  up data
                type: string
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
