---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: kind-default
    groups:
      - k8s
    image: bsycorp/kind:latest-1.14
    privileged: True
    override_command: no
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-9443}:8443/tcp
    pre_build_image: yes
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        operator_namespace: ${TEST_NAMESPACE:-default}
