---
- name: Build and Deploy the AWX Operator
  hosts: localhost

  collections:
    - community.docker

  tasks:
    - name: Build and (optionally) push operator image
      docker_image:
        name: "{{ operator_image }}:{{ operator_version }}"
        source: "build"
        push: "{{ push_image }}"
        build:
          dockerfile: "build/Dockerfile"
          path: "../"
        force_source: "yes"
