---
# To run: `ansible-playbook chain-operator-files.yml`
- name: Chain operator files together for easy deployment.
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Template AWX CRD
      template:
        src: crd.yml.j2
        dest: "{{ playbook_dir }}/../deploy/crds/awx_v1beta1_crd.yaml"
        mode: '0644'

    - name: Template AWXBackup CRD
      template:
        src: awxbackup_crd.yml.j2
        dest: "{{ playbook_dir }}/../deploy/crds/awxbackup_v1beta1_crd.yaml"
        mode: '0644'

    - name: Template AWXRestore CRD
      template:
        src: awxrestore_crd.yml.j2
        dest: "{{ playbook_dir }}/../deploy/crds/awxrestore_v1beta1_crd.yaml"
        mode: '0644'

    - name: Template awx-operator.yaml
      template:
        src: awx-operator.yaml.j2
        dest: ../deploy/awx-operator.yaml
        mode: '0644'
