---
- name: Deploy an instance of AWX using the awx-operator
  hosts: localhost

  collections:
    - community.kubernetes

  tasks:
    - name: Deploy AWX
      k8s:
        state: "{{ state | default('present') }}"
        namespace: "{{ tower_namespace | default('default') }}"
        apply: yes
        wait: yes
        definition:
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
          spec:
            tower_admin_user: admin
            tower_admin_email: admin@localhost
            tower_ingress_type: "{{ tower_ingress_type | default(omit) }}"  # Either Route, Ingress or LoadBalancer
            tower_image: "{{ tower_image | default(omit) }}"
            tower_image_version: "{{ tower_image_version | default(omit) }}"
            development_mode: "{{ development_mode | default(omit) | bool }}"
            tower_image_pull_policy: "{{ tower_image_pull_policy | default(omit) }}"
            # tower_ee_images:
            #   - name: test-ee
            #     image: quay.io/<user>/awx-ee
