---

name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-18.04
    name: Push tagged image to Quay
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          IMG=awx-operator:${{ github.event.release.tag_name }} make docker-build

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: awx-operator
          tags: ${{ github.event.release.tag_name }}
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
